### PR TITLE
Unit test prototype

### PR DESCRIPTION
**Pull request by halueda**
A unit test file is prepared.
Just one test is added.
The test is passed.

### CODE REVIEW

**Comment by ChillarAnand** [comment]
@halueda  Thank you for this test. Adding one test per file looks good.

We can have 4 unit tests
- real auto save turns on
- starts timer
- saves buffer
- killed buffers gets removed from list

Also instead or running tests by opening file and running them, we can use  `Makefile` & `cask`

```
test:
    cask exec ert-runner --quiet
```

```
(development
 (depends-on "ert-runner"))
```

So that we can run tests from command line using `make test`. What do you think?

**Comment by halueda** [comment]
I intended to prepare an appropriate file to avoid conflict, but not one test per file.
I think one test file  per one source file is a little easier to maintain.

Makefile and cask is very good idea.

I’m not familiar with cask, that
could you add Makefile and configuration file for cask?

**Comment by ChillarAnand** [comment]
@halueda Sorry for delay. 

Sure. I will add Make & Cask files by evening!

**Comment by ChillarAnand** [comment]
Added  cask & make files

**Comment by ChillarAnand** [comment]
Thanks @halueda

**Pull request merged**
